apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- web-deployment.yaml
- web-service.yaml
images:
- name: 4e06a9e9-kr1-registry.container.nhncloud.com/ncr-for-web/nginx
  newTag: 20240911063140-1388dd9
- name: 4e06a9e9-kr1-registry.container.nhncloud.com/ncr-for-web/was
  newTag: 20240913014805-3b5aef1
