apiVersion: v1
kind: Service
metadata:
  name: was-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: was
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
